apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /home/dev-scripts/nfs_share
    server: 10.0.0.3
  persistentVolumeReclaimPolicy: Retain 