apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ctlplane
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ctlplane",
      "type": "ipvlan",
      "master": "enp2s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.10.10.0/24",
        "range_start": "172.10.10.30",
        "range_end": "172.10.10.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: internalapi
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "internalapi",
      "type": "ipvlan",
      "master": "enp3s0",
      "mode": "l2",
      "ipam": { 
        "type": "whereabouts", 
        "range": "172.10.20.0/24",
        "range_start": "172.10.20.30", 
        "range_end": "172.10.20.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: storage
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "storage",
      "type": "ipvlan",
      "master": "enp4s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.10.30.0/24",
        "range_start": "172.10.30.30",
        "range_end": "172.10.30.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ospmgmt
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "ospmgmt",
      "type": "ipvlan",
      "master": "enp10s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.10.40.0/24",
        "range_start": "172.10.40.30",
        "range_end": "172.10.40.70"
      }
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: tenant
  namespace: openstack
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "tenant",
      "type": "ipvlan",
      "master": "enp5s0",
      "mode": "l2",
      "ipam": {
        "type": "whereabouts",
        "range": "172.10.50.0/24",
        "range_start": "172.10.50.30",
        "range_end": "172.10.50.70"
      }
    }