apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  namespace: openstack
spec:
  containers:
  - name: httpd-container
    image: registry.redhat.io/rhel9/httpd-24
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: data-volume
      mountPath: /var/www/html/repo  # This is your specific mount point
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: isodv-2  # This is the name of the PVC created by your DataVolume
