---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    #k8s.v1.cni.cncf.io/networks: 'ctlplane'
  name: yum-repo-server
  labels:
    app: yum-repo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yum-repo-server
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 1 
      intervalSeconds: 1 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "10%" 
      pre: {} 
      post: {}
  template:
    metadata:
      labels:
        app: yum-repo-server
      annotations:
        k8s.v1.cni.cncf.io/networks: 'ctlplane'
    spec:
      containers:
      - image: registry.redhat.io/ubi9/httpd-24
        imagePullPolicy: Always
        name: httpd-rhel7
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 8443
          name: https-port
        volumeMounts:
          - name: httpd-persistent-storage # This name must match a volume defined below
            mountPath: /var/www/html # The full path where the file will appear
      volumes:
      - name: httpd-persistent-storage # This name is referenced by the volumeMounts
        persistentVolumeClaim:
          claimName: isodv-2
---
apiVersion: v1
kind: Service
metadata:
  name: http-port
  labels:
    app: yum-repo-server
spec:
  ports:
    - port: 8080
      name: http-port
      protocol: TCP
      targetPort: 8080
  selector:
    app: yum-repo-server

